[project]
name = "linkedin-games"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=12.0.2",
    "ortools>=9.14.6206",
    "playwright>=1.53.0",
    "pydantic>=2.11.7",
]
